### PR TITLE
Make integration compatible with older Magento versions

### PR DESCRIPTION
**Pull request by specikrumpel**
In order to achieve compatibility with older versions, I had to modify the class that returns our custom GraphQL attribute. From now on, it works in such a way that if we don't have the required classes (version 2.4.6 and lower), we will always return "null" in that attribute; otherwise, we will return the product custom attributes.

Part of this solution also involved changing the type we return. Until now, we have been returning a value of the type `ProductCustomAttributes`, but now we return String, because type `ProductCustomAttributes` doesnt exist in older versions. String can hold both "null" and custom attributes parsed as JSON string, and i dont need to bother with some custom types (because GraphQL doesnt have a native Hash type).

### CODE REVIEW

**Review by crutch — APPROVED** [review]
Looks good to me (to the extent I am able to evaluate it). Please bump version in the composer as well, so that when this will be merged (you can merge it) we will have a bumped version in the master.

**Comment by crutch** [comment]
Also, can we publish it before the new app code is released?

**Comment by specikrumpel** [comment]
@crutch i bumped the version from 1.0.0 to 1.1.0, let me know if thats fine.

And im not sure if i understand the second question. What is the difference between publishing and releasing app code?

**Comment by crutch** [comment]
The version bump is OK. Thanks. The second part - I was just wondering whether we have to release this update before we merge & release the synchronizer ruby code into production. But now I realize that the synchronizer code must be able to work with older version of the plugin (1.0.0) because we cannot expect all the installation to upgrade quickly.

**Comment by crutch** [comment]
So basically the question is whether our new synchronizer code 
https://github.com/luigisbox/luigisbox/pull/2831
can work with older version of the plugin

**Comment by specikrumpel** [comment]
@crutch I added a small change to our synchronizer code, so that it also works with extension v. 1.0.0, so we can deploy synchronizer now, and this PR can get deployed and published whenever

**Pull request merged**
